export const useDummiesDataStore = {
  users: [
    {
      id: 1,
      name: "Jarwo Kuat",
      email: "jarwo@example.com",
      username: "jarwo123",
    },
    {
      id: 2,
      name: "Adit Ramdhan",
      email: "adit@example.com",
      username: "adit123",
    },
    {
      id: 3,
      name: "Togar Abdurahman",
      email: "togar@example.com",
      username: "togar123",
    },
    {
      id: 4,
      name: "Nabilla Pradisa",
      email: "nabilla@example.com",
      username: "nabilla123",
    },
    {
      id: 5,
      name: "Kurniawan Pratama",
      email: "kurniawan@example.com",
      username: "kurniawan123",
    },
  ],

  categories: [
    { id: 1, name: "Makanan" },
    { id: 2, name: "Kopi" },
    { id: 3, name: "Minuman" },
    { id: 4, name: "Teh" },
    { id: 5, name: "Cemilan" },
  ],

  products: [
    // ===== MAKANAN =====
    {
      id: 1,
      name: "Nasi Goreng Spesial",
      category: "makanan",
      desc: "Nasi goreng dengan telur, ayam suwir, dan bumbu khas.",
      price: 25000,
      recommended: true,
      pupular: true,
    },
    {
      id: 2,
      name: "Ayam Bakar Madu",
      category: "makanan",
      desc: "Ayam bakar empuk dengan olesan madu manis gurih.",
      price: 32000,
      recommended: true,
      pupular: false,
    },
    {
      id: 3,
      name: "Mie Goreng Jawa",
      category: "makanan",
      desc: "Mie goreng tradisional dengan aroma khas jawa.",
      price: 22000,
      recommended: false,
      pupular: true,
    },
    {
      id: 4,
      name: "Sate Ayam",
      category: "makanan",
      desc: "Sate ayam dengan bumbu kacang kental.",
      price: 30000,
      recommended: true,
      pupular: true,
    },
    {
      id: 5,
      name: "Rendang Daging",
      category: "makanan",
      desc: "Daging sapi dimasak lama dengan rempah pilihan.",
      price: 40000,
      recommended: false,
      pupular: false,
    },
    {
      id: 6,
      name: "Ayam Geprek",
      category: "makanan",
      desc: "Ayam crispy geprek dengan sambal pedas.",
      price: 28000,
      recommended: true,
      pupular: true,
    },
    {
      id: 7,
      name: "Nasi Ayam Teriyaki",
      category: "makanan",
      desc: "Ayam saus teriyaki manis dengan nasi hangat.",
      price: 27000,
      recommended: false,
      pupular: true,
    },
    {
      id: 8,
      name: "Bakso Urat",
      category: "makanan",
      desc: "Bakso urat sapi dengan kuah kaldu gurih.",
      price: 23000,
      recommended: false,
      pupular: true,
    },
    {
      id: 9,
      name: "Ikan Bakar",
      category: "makanan",
      desc: "Ikan segar dibakar dengan bumbu nusantara.",
      price: 35000,
      recommended: true,
      pupular: false,
    },
    {
      id: 10,
      name: "Nasi Rawon",
      category: "makanan",
      desc: "Rawon daging sapi dengan kuah hitam khas.",
      price: 33000,
      recommended: true,
      pupular: false,
    },

    // ===== MINUMAN =====
    {
      id: 11,
      name: "Es Teh Manis",
      category: "minuman",
      desc: "Teh dingin manis yang menyegarkan.",
      price: 8000,
      recommended: false,
      pupular: true,
    },
    {
      id: 12,
      name: "Es Jeruk",
      category: "minuman",
      desc: "Jeruk segar diperas dengan es batu.",
      price: 10000,
      recommended: true,
      pupular: true,
    },
    {
      id: 13,
      name: "Kopi Susu Gula Aren",
      category: "minuman",
      desc: "Kopi susu dengan gula aren asli.",
      price: 18000,
      recommended: true,
      pupular: true,
    },
    {
      id: 14,
      name: "Matcha Latte",
      category: "minuman",
      desc: "Matcha lembut berpadu susu creamy.",
      price: 20000,
      recommended: true,
      pupular: false,
    },
    {
      id: 15,
      name: "Jus Alpukat",
      category: "minuman",
      desc: "Jus alpukat kental dan mengenyangkan.",
      price: 22000,
      recommended: false,
      pupular: false,
    },
    {
      id: 16,
      name: "Jus Mangga",
      category: "minuman",
      desc: "Jus mangga manis alami dan segar.",
      price: 20000,
      recommended: false,
      pupular: true,
    },
    {
      id: 17,
      name: "Thai Tea",
      category: "minuman",
      desc: "Teh susu khas Thailand yang creamy.",
      price: 18000,
      recommended: true,
      pupular: true,
    },
    {
      id: 18,
      name: "Lemon Tea",
      category: "minuman",
      desc: "Teh dengan rasa lemon segar.",
      price: 15000,
      recommended: false,
      pupular: false,
    },
    {
      id: 19,
      name: "Cappuccino",
      category: "minuman",
      desc: "Kopi espresso dengan foam susu.",
      price: 22000,
      recommended: true,
      pupular: false,
    },
    {
      id: 20,
      name: "Air Mineral",
      category: "minuman",
      desc: "Air mineral murni dan menyegarkan.",
      price: 6000,
      recommended: false,
      pupular: true,
    },

    // ===== CEMILAN =====
    {
      id: 21,
      name: "Kentang Goreng",
      category: "cemilan",
      desc: "Kentang goreng renyah dan gurih.",
      price: 15000,
      recommended: true,
      pupular: true,
    },
    {
      id: 22,
      name: "Tahu Crispy",
      category: "cemilan",
      desc: "Tahu goreng tepung renyah.",
      price: 12000,
      recommended: true,
      pupular: false,
    },
    {
      id: 23,
      name: "Pisang Goreng Keju",
      category: "cemilan",
      desc: "Pisang goreng dengan topping keju.",
      price: 14000,
      recommended: false,
      pupular: true,
    },
    {
      id: 24,
      name: "Cireng Isi",
      category: "cemilan",
      desc: "Cireng renyah dengan isian ayam pedas.",
      price: 10000,
      recommended: true,
      pupular: true,
    },
    {
      id: 25,
      name: "Donat Gula",
      category: "cemilan",
      desc: "Donat empuk dengan taburan gula.",
      price: 9000,
      recommended: false,
      pupular: false,
    },
    {
      id: 26,
      name: "Risoles Mayo",
      category: "cemilan",
      desc: "Risoles isi mayo dan ayam.",
      price: 13000,
      recommended: true,
      pupular: true,
    },
    {
      id: 27,
      name: "Singkong Keju",
      category: "cemilan",
      desc: "Singkong goreng empuk bertabur keju.",
      price: 14000,
      recommended: false,
      pupular: true,
    },
    {
      id: 28,
      name: "Bakwan Jagung",
      category: "cemilan",
      desc: "Bakwan jagung gurih dan renyah.",
      price: 10000,
      recommended: false,
      pupular: false,
    },
    {
      id: 29,
      name: "Chicken Nugget",
      category: "cemilan",
      desc: "Nugget ayam crispy disajikan hangat.",
      price: 16000,
      recommended: true,
      pupular: true,
    },
    {
      id: 30,
      name: "Sosis Bakar",
      category: "cemilan",
      desc: "Sosis bakar dengan saus manis pedas.",
      price: 12000,
      recommended: true,
      pupular: false,
    },
  ],

  merchants: [
    { id: 1, name: "Gojek", desc: "http://gojek.com/orangebox" },
    { id: 2, name: "Grab", desc: "http://grab.com/orangebox" },
    { id: 3, name: "Shoppee", desc: "http://shoopee.com/orangebox" },
    { id: 4, name: "Kami", desc: "0838 xxxx xxxx" },
  ],

  testimonies: [
    {
      id: 1,
      name: "Bernadya",
      desc: "Pas banget buat nongkrong.",
    },
    {
      id: 2,
      name: "Abdul Kodir",
      desc: "Paling cocok kalo bawa keluarga.",
    },
    {
      id: 3,
      name: "Nathan",
      desc: "Live musik-nya bikin asik.",
    },
    {
      id: 4,
      name: "Bisul Antik",
      desc: "Harganya murah-murah banget.",
    },
  ],

  umkm: {
    name: "orangebox",
    address: "",
    title: "",
    description: "",
    cta: "",
    location: "",

    phone: "",
    email: "",
    whatsapp: "",
  },
};
